### ISSUE TITLE
Can't pay for subscription

### ISSUE THREAD

**Issue by markmcd** [Reviewable/Reviewable#179]
While entering my credit card details and clicking Subscribe I got this error:

Failed to update subscription: {}

**Comment by pkaminski** [comment]
Sorry about that @markmcd.  Looks like your client wasn't able to enqueue the subscription request to the server for some reason.  While I investigate, could you please try hitting "Confirm" again to see if it's a transient error?  Thanks.

**Comment by markmcd** [comment]
Nope, still happening.

**Comment by pkaminski** [comment]
Are you trying to set the subscription's scope to "just members of this team"?

**Comment by pkaminski** [comment]
I fixed a really silly bug in the only repro I could find, so hopefully this should now work.  Please let me know.

**Comment by markmcd** [comment]
I am setting "just members of this team" and I'm still seeing that error :(

**Comment by pkaminski** [comment]
Did you reload the page? The bug was client-side.

  Piotr Kaminski, Founder at Reviewable. io

**Comment by markmcd** [comment]
Ahh - much better. Thank you.

**Comment by pkaminski** [comment]
Great!  And my apologies for letting that bug slip through.  :disappointed:
